# Generated by Django 5.0.4 on 2024-05-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='is_activated',
        ),
    ]
