# Generated by Django 5.0.4 on 2024-05-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rs',
            options={'ordering': ['-created_at'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterField(
            model_name='rs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Добавлено'),
        ),
    ]
